spring:
  application:
    name: Profile-Service

  cache:
    type: redis
  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOSt:localhost}

  datasource:
    url: jdbc:mysql://mysql-db:3306/profiledb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8082}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

secret:
  header:
    key: ${SECRET_HEADER_KEY}

